web/router.ex
defmodule Isis.Router do
  use Phoenix.Router
  use Phoenix.Router.Socket, mount: "/ws"

  pipeline :browser do
    plug :accepts, ~w(html)
    plug :fetch_session
  end

  pipeline :api do
    plug :accepts, ~w(json)
  end

  scope "/", Isis do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    
    get "/login", SessionController, :new, as: :login
    post "/login", SessionController, :create, as: :login
    delete "/logout", SessionController, :destroy, as: :login
    
    resources "users", UserController, as: :user, only: [:new, :create]
    resources "projects", ProjectController, as: :project, only: [:new, :create]
  end
  
  channel "robots", Isis.RobotChannel

  # Other scopes may use custom stacks.
  # scope "/api", Isis do
  #   pipe_through :api
  # end
end

lib/isis/endpoint.ex
defmodule Isis.Endpoint do
  use Phoenix.Endpoint, otp_app: :isis

  plug Plug.Static,
    at: "/", from: :isis

  plug Plug.Logger

  # Code reloading will only work if the :code_reloader key of
  # the :phoenix application is set to true in your config file.
  plug Phoenix.CodeReloader

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_isis_key",
    signing_salt: "oDh7VASh",
    encryption_salt: "ZPr6VL24"

  plug :router, Isis.Router
end

web/models/repo.ex
defmodule Isis.Repo do
  use Ecto.Repo, adapter: Ecto.Adapters.Postgres, env: Mix.env
  
  @doc "Adapter configuration"
  def conf(env), do: parse_url url
  
  defp url do
    Application.get_env(:phoenix, :database)[:url]
  end

  def priv do
    app_dir(:isis, "priv/repo")
  end
end

web/models/user.ex
defmodule Isis.User do
  use Ecto.Model

  schema "users" do
    field :email, :string
    field :password, :string
    field :created_at, :datetime, default: Ecto.DateTime.local
    field :updated_at, :datetime, default: Ecto.DateTime.local
  end
  
  # Isis.User.validate(%Isis.User{})
  # => %{email: ["can't be blank"], password: ["must be present"]}
  validate user,
    also: validate_password,
    also: validate_email
    
  validatep validate_email(user),
    email: present() and has_format(~r"^[^@]+@[^@]+\.[^@]+$")

  validatep validate_password(user),
    password: present()
    
  def create(params) do
    email    = if is_binary(params[:email]), do: String.downcase(params[:email]), else: params[:email]
    password = params[:password]
    now      = Ecto.DateTime.utc
    user     = %Isis.User{email: email, password: password,
                          created_at: now, updated_at: now}
    
    case validate(user) do
      nil ->
        user = %{user | password: gen_password(password)}
        { :ok, Isis.Repo.insert(user) }
      errors ->
        { :error, Enum.into(errors, %{}) }
    end
  end
  
  def update(user, params) do
    errors = []
    email    = if is_binary(params[:email]), do: String.downcase(params[:email]), else: params[:email]
    password = params[:password]
    if email do
      user = %{user | email: String.downcase(email)}
      if v = validate_email(user) do errors = errors ++ v end
    end
    if password && String.length(password) > 0 do
      user = %{user | password: password}
      if v = validate_password(user) do errors = errors ++ v end
      user = %{user | password: gen_password(password)}
    end
    case errors do
      [] ->
        user = %{user | updated_at: Ecto.DateTime.utc}
        Isis.Repo.update(user)
        { :ok, user }
      errors ->
        { :error, Enum.into(errors, %{}) }
    end
  end
  
  def get(nil), do: nil
  
  def get(email) do
    from(u in Isis.User,
         where: downcase(u.email) == downcase(^email),
         limit: 1)
    |> Isis.Repo.all
    |> List.first
  end
  
  def auth?(nil, _password), do: false
  
  def auth?(user, password) do
    stored_hash   = user.password
    password      = String.to_char_list(password)
    stored_hash   = :erlang.binary_to_list(stored_hash)
    { :ok, hash } = :bcrypt.hashpw(password, stored_hash)
    hash == stored_hash
  end
  
  defp gen_password(password) do
    password      = String.to_char_list(password)
    work_factor   = 4
    { :ok, salt } = :bcrypt.gen_salt(work_factor)
    { :ok, hash } = :bcrypt.hashpw(password, salt)
    :erlang.list_to_binary(hash)
  end
  
end

web/controllers/page_controller.ex
defmodule Isis.PageController do
  use Isis.Helper.Application

  plug :action

  def index(conn, _params) do
    render conn, "index.html", %{title: "Welcome"}
  end
end

web/controllers/project_controller.ex
defmodule Isis.ProjectController do
  use Isis.Helper.Application
  alias Isis.User
  alias Plug.Conn
  
  plug :authorize
  plug :action
  
  def new(conn, params) do
    render conn, "new.html", %{title: "Project"}
  end
  
  def create(conn, params) do
    # talking with the robots on the lab. by now we just have 1 robot
    case Node.list do
      [] ->
        conn = Flash.put(conn, :warning, "Arc is sleeping. Send a message to my masters at team@arcturus.io")
        messages = Flash.get(conn)
        render conn, "new.html", %{title: "Project", flash_messages: messages, livestreaming: false}
      _ ->
        robot_node = hd(Node.list)
        cmd = "/bin/bash /root/horus/robot-scripts/modular-science/experiment.sh"
        # cmd = "/bin/bash /Users/luisbebop/Documents/arcturusbiocloud/horus/robot-scripts/modular-science/experiment.sh"
        # cmd = "ping www.google.com"
        Horus.Client.shell(cmd, robot_node)
                        
        conn = Flash.put(conn, :notice, "Project created. Arc is working for you. Check the live streaming.")
        messages = Flash.get(conn)
        render conn, "new.html", %{title: "Project", flash_messages: messages, livestreaming: true}
    end
  end

end

web/controllers/session_controller.ex
defmodule Isis.SessionController do
  use Isis.Helper.Application
  alias Isis.User
  alias Plug.Conn
  
  plug :action

  def new(conn, _params) do
    if conn.assigns[:current_user] do
      conn
      |> redirect to: Isis.Router.Helpers.page_path(:index)
    else
      render conn, "new.html", %{title: "Log In"}
    end
  end
  
  def create(conn, params) do
    user = User.get(params["email"])
    if User.auth?(user, params["password"]) do
      conn
      |> Conn.fetch_session
      |> Conn.put_session(:email, user.email)
      |> Flash.put(:notice, "Logged in as #{user.email}")
      |> redirect to: Isis.Router.Helpers.page_path(:index)
    else
      conn = Flash.put(conn, :warning, "Please re-enter your password")
      messages = Flash.get(conn)
      render conn, "new.html", %{title: "Log In", flash_messages: messages}
    end
  end
  
  def destroy(conn, _params) do
    conn
    |> Conn.fetch_session
    |> Conn.delete_session(:email)
    |> Flash.put(:notice, "Logged out")
    |> redirect to: Isis.Router.Helpers.page_path(:index)
  end

end

web/controllers/user_controller.ex
defmodule Isis.UserController do
  use Isis.Helper.Application
  alias Isis.User
  alias Plug.Conn
  
  plug :action
  
  def new(conn, _params) do
    if conn.assigns[:current_user] do
      conn
      |> redirect to: Isis.Router.Helpers.page_path(:index)
    else
      render conn, "new.html", %{title: "Sign Up", user: %User{}}
    end
  end
  
  def create(conn, params) do
    sanitized_params = sanitize_params(User, params)
    result = User.create(sanitized_params)
    case result do
      { :ok, user } ->
        conn
        |> Conn.fetch_session
        |> Conn.put_session(:email, user.email)
        |> Flash.put(:notice, "User #{user.email} created")
        |> redirect to: Isis.Router.Helpers.page_path(:index)
      { :error, errors } ->
        render conn, "new.html", %{title: "Sign Up", user: sanitized_params, errors: errors}
    end
  end
  
end

web/views/error_view.ex
defmodule Isis.ErrorView do
  use Isis.View

  def render("404.html", _assigns) do
    "Page not found - 404"
  end

  def render("500.html", _assigns) do
    "Server internal error - 500"
  end

  # Render all other templates as 500
  def render(_, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Isis.LayoutView do
  use Isis.View
end

web/views/page_view.ex
defmodule Isis.PageView do
  use Isis.View
end

web/views/project_view.ex
defmodule Isis.ProjectView do
  use Isis.View
end

web/views/session_view.ex
defmodule Isis.SessionView do
  use Isis.View
end

web/views/user_view.ex
defmodule Isis.UserView do
  use Isis.View
end

web/templates/layout/application.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Arcturus BioCloud - <%= @title %></title>
    
    <link href='/images/favicon.ico' rel='shortcut icon'>
    <link href='/images/default.png' rel='apple-touch-icon-precomposed'>
    <link href="/css/dist/semantic.min.css" rel="stylesheet" type="text/css"/>
    <link href="/css/main.css" rel="stylesheet" type="text/css"/>
  </head>

  <body id="main">
<%= @inner %>
  </body>
</html>

web/templates/page/error.html.eex
Something went wrong

web/templates/page/index.html.eex
<div class="ui page grid">
  <div class="sixteen wide column">    
    <div class="ui segment">
      <div class="ui three column grid">
        <div class="column">
          <img class="ui image" src="/images/default.png">
        </div>
        <div class="column">
          <div class="ui large breadcrumb">
            <div class="active section">Projects</div>
            <i class="right chevron icon divider"></i>
            <a class="section">People</a>
            <i class="right chevron icon divider"></i>
            <a class="section">Explore</a>
            <i class="right chevron icon divider"></i>
            <a class="section">Learning</a>
          </div>
        </div>
        <div class="column right aligned">
          <%= if @current_user do %>
            <a href="/logout" data-method="DELETE" rel="nofollow">Logout</a>
          <% else %>
            <a href="/login">Login</a>
          <% end %>
        </div>
      </div>
    </div>
    
    <%= for notice <- Flash.get_all(@conn, :notice) do %>
    <div class="ui warning small message">
      <i class="close icon"></i>
      <div class="header" id="warning-message">
        <%= notice %>
      </div>
    </div>
    <% end %>
    
    <div class="ui form segment left aligned">     
      <div class="column">
        <%= if @current_user do %>
        <a class="ui green button" href="<%= project_path(:new) %>">New Project</a>
        <% else %>
        <h4>Welcome to Arcturus BioCloud. Please <a href="/login">login</a> to create a new project.</h4>
        <% end %>
      </div>
    </div>
    
  </div>
</div>

<script src="/js/jquery-1.11.2.min.js"></script>
<script src="/js/restfulizer.js"></script>

<script>
  (function ($) {    
    $(".close.icon").click(function(){
      $(this).parent().hide();
    });
  }(jQuery));
</script>

web/templates/page/not_found.html.eex
The page you are looking for does not exist

web/templates/project/new.html.eex
<div class="ui page grid">
  <div class="sixteen wide column">    
    <div class="ui segment">
      <div class="ui three column grid">
        <div class="column">
          <img class="ui image" src="/images/default.png">
        </div>
        <div class="column">
          <div class="ui large breadcrumb">
            <div class="active section">Projects</div>
            <i class="right chevron icon divider"></i>
            <a class="section">People</a>
            <i class="right chevron icon divider"></i>
            <a class="section">Explore</a>
            <i class="right chevron icon divider"></i>
            <a class="section">Learning</a>
          </div>
        </div>
        <div class="column right aligned">
          <%= if @current_user do %>
            <a href="/logout" data-method="DELETE" rel="nofollow">Logout</a>
          <% else %>
            <a href="/login">Login</a>
          <% end %>
        </div>
      </div>
    </div>
    
    <%= for warning <- Flash.get_all(@conn, :warning) do %>
    <div class="ui negative small message">
      <i class="close icon"></i>
      <div class="header" id="warning-message">
        <%= warning %>
      </div>
    </div>
    <% end %>
    
    <%= for notice <- Flash.get_all(@conn, :notice) do %>
    <div class="ui warning small message">
      <i class="close icon"></i>
      <div class="header" id="warning-message">
        <%= notice %>
      </div>
    </div>
    <% end %>
        
    <form class="ui form segment left aligned" action="<%= project_path(:create) %>" method="post"> 
      <h4 class="ui header">Tell to Arc how will be your genetic project. Arc understand plain english.</h4>
      <div class="field">
        <label></label>
        <textarea>Please Arc,
          
Mix the plasmid p_GLO with a e.coli bacteria to make it glow, following the Arcturus Glowing Bacteria protocol.
Send me an email with the pictures and luminescence data every 4 hours.
After 12 hours delivery the petri dish to my home if the bacteria is glowing, otherwise throw it away.</textarea>
      </div>
     
      <div class="column">
      <%= if @livestreaming do %>
        <a class="ui red button" href="<%= project_path(:new) %>">Stop</a>
     <%= else %>
        <input type="submit" class="ui green button" name="submit" value="Execute"/>
      <% end %>
      </div>
      
      <%= if @livestreaming do %>
      <h4 class="ui header">Output log</h4>
      <div class="field">
        <label></label>
        <textarea id="console" readonly></textarea>
      </div>
      <h4 class="ui dividing header">Live Streaming</h4>
      <div id="strobeMediaPlayback">
        <p>Live Streaming not supported in your browser.</p>
      </div>
      <% end %>
    </form>
    
    <%= unless @livestreaming do %>
    <div class="ui segment">
    <img class="ui medium right floated image" src="/images/robot.png">
    <p>&nbsp</p><p>&nbsp</p>
    <p>Hi! I'm Arc, the robot, from the Boötes constellation. I was brought to planet Earth and trained by my masters to help you create amazing genetic experiments that will save your world.</p>
    <p>In the ancient past, earthly scientists used to do everything by hand using expensive labs, chemicals and complicated primitive machines. Without my help, pain and frustration assolated their postdocs careers and projects.</p>
    <p>I'm perfect, fast and precise. Using my robot brain, I can even create and manage experiment data for you. I have experience creating glowing bacterias, quantum computers, jellyfishes, and cup cakes.</p>
    <p>Shall we start? Let's create some life together!</p>
    </div>
    <% end %>
        
  </div>
</div>

<script src="/js/jquery-1.11.2.min.js"></script>
<script src="/js/restfulizer.js"></script>

<script>
  (function ($) {    
    $(".close.icon").click(function(){
      $(this).parent().hide();
    });
  }(jQuery));
</script>

<%= if @livestreaming do %>
<script type="text/javascript" src="/js/strobe/lib/swfobject.js"></script>
<script type="text/javascript">        
  // Create a StrobeMediaPlayback configuration 
  var parameters = {  
                      src: "rtmp://osiris.arcturus.io/flvplayback/myStream",  
                      autoPlay: true,  
                      controlBarAutoHide: false,  
                      playButtonOverlay: true,  
                      showVideoInfoOverlayOnStartUp: true,  
                      optimizeBuffering : false,  
                      initialBufferTime : 0.1,  
                      expandedBufferTime : 0.1,  
                      minContinuousPlayback : 0.1,  
                      streamType: "live",
                      poster: "/js/strobe/images/poster.png"  
                    };  
      
  // Embed the player SWF:          
  swfobject.embedSWF
     ( "/js/strobe/StrobeMediaPlayback.swf"
     , "strobeMediaPlayback"
     , 800
     , 600
     , "10.1.0"
     , {}
     , parameters
     , { allowFullScreen: "true"}
     , { name: "strobeMediaPlayback" }
     );
</script>

<script type="text/javascript" src="/js/phoenix.js"></script>
<script type="text/javascript">
  $(function(){  
    var socket = new Phoenix.Socket("ws://" + location.host +  "/ws");
    socket.join("robots", "lobby", {}, function(chan){
      chan.on("join", function(data){
        console.log(data.status);
      });

      chan.on("new:msg", function(data){
        $("textarea#console").append(data.msg);
        var psconsole = $("textarea#console");
        if(psconsole.length) psconsole.scrollTop(psconsole[0].scrollHeight - psconsole.height());
      });

    });
  });
</script>
<% end %>

web/templates/session/new.html.eex
    <div class="login-form">
      <div class="ui one column stackable center aligned page grid">
        <div class="column nine wide">
          <form class="ui form segment left aligned" action="/login" method="post">
            <div class="ui icon header blue center aligned">
              <img src="/images/arcturus-logo-shadown.jpg" alt="Arcturus BioCloud logo">
              <!-- <img src="/images/arcturus-logo-flat.png" alt="Arcturus BioCloud logo"> -->

              <div class="content">
                Log In
                <div class="sub header">Access your Arcturus BioCloud dashboard</div>   
              </div>
            </div>
            
            <%= for warning <- Flash.get_all(@conn, :warning) do %>
            <div class="ui negative small message">
              <i class="close icon"></i>
              <div class="header" id="warning-message">
                <%= warning %>
              </div>
              <p>The password or email you entered is incorrect. Please try again (make sure your caps lock is off).</p>
            </div>
            <% end %>
  
            <div class="field">
              <label for="Email">Email</label>
              <input type="text" id="Email" name="email" placeholder="Email" >
            </div>

            <div class="field">
              <label for="Password">Password</label>
              <div class="ui left icon input">
                <i class="lock icon"></i>
                <input type="password" id="Password" name="password">
              </div>
            </div>

            <div class="center aligned column">
              <div class="ui buttons">
                <!-- <a class="ui blue submit button">Log In</a> -->
                <input type="submit" class="ui blue button" name="submit" value="Log In"/>
                <div class="or"></div>
                <a class="ui green button" href="<%= user_path(:new) %>">Sign Up</a>
              </div>
            </div>
          </form>           
        </div>
      </div>
    </div>

    <script src="/js/jquery-1.11.2.min.js"></script>
    <script src="/css/dist/semantic.min.js"></script>
    <script>
      (function ($) {
        
        $('.ui.form').form({             
          email: {
            identifier: 'Email',
            rules: [{
              type: 'empty',
              prompt: 'Please enter your email'
            },{
              type: 'email',
              prompt: 'Please enter a valid email'
            }]
          },   
          password: {
            identifier: 'Password',
            rules: [{
              type: 'empty',
              prompt: 'Please enter a password'
            },{
              type: 'length[6]',
              prompt: 'Password needs to be at least 6 characters long'
            }]
          }
        }, {
          on: 'blur',
          inline: 'true'
        });
        
        $(".close.icon").click(function(){
          $(this).parent().hide();
        });
        
      }(jQuery));
    </script>

web/templates/user/new.html.eex
    <div class="signup-form">
      <div class="ui one column stackable center aligned page grid">
        <div class="column nine wide">
          <form class="ui form segment left aligned" action="<%= user_path(:create) %>" method="post">  
            <div class="ui icon header blue center aligned">
              <img src="/images/arcturus-logo-shadown.jpg" alt="Arcturus BioCloud logo">
              <!-- <img src="img/arcturus-logo-flat.png" alt="Arcturus BioCloud logo"> -->
              
              <div class="content">
                Sign Up
                <div class="sub header">Create your Arcturus BioCloud profile</div>   
              </div>
            </div>
            
            <%= if @errors do %>
            <div class="ui negative small message">
              <i class="close icon"></i>
              <div class="header" id="warning-message">
                The following errors were found:
              </div>
              <ul> 
              <%= format_error(@errors) %> 
              </ul>
            </div>
            <% end %>
               
            <div class="field">
              <label for="Email">Email</label>
              <input id="Email" placeholder="Email" type="text" name="email" value="<%= @user.email %>">
            </div>
    
            <div class="field">
              <label for="EmailConfirm">Re-enter email</label>
              <input id="EmailConfirm" placeholder="Re-enter email" type="text" name="emailconfirm" value="<%= @user.email %>">
            </div>

            <div class="field">
              <label for="Password">New password</label>
              <div class="ui left icon input">
                <i class="lock icon"></i>
                <input id="Password" type="password" name="password">
              </div>
            </div>
    
            <div class="field">
              <label for="PasswordConfirm">Re-enter password</label>
              <div class="ui left icon input">
                <i class="lock icon"></i>
                <input id="PasswordConfirm" type="password" name="passwordconfirm">
              </div>
            </div>
      
            <div class="center aligned column">
              <input type="submit" class="ui green button" name="submit" value="Sign Up"/>
            </div>
          </form>
        </div>
      </div>  
    </div>

    <script src="/js/jquery-1.11.2.min.js"></script>
    <script src="/css/dist/semantic.min.js"></script>
    <script>
      (function ($) {
        $('.ui.form').form({             
          email: {
            identifier: 'Email',
            rules: [{
              type: 'empty',
              prompt: 'Please enter your email'
            },{
              type: 'email',
              prompt: 'Please enter a valid email'
            }]
          },
          emailConfirm: {
            identifier: 'EmailConfirm',
            rules: [{
              type: 'match[Email]',
              prompt: 'Email don\'t match'
            }]
          },       
          password: {
            identifier: 'Password',
            rules: [{
              type: 'empty',
              prompt: 'Please enter a password'
            },{
              type: 'length[6]',
              prompt: 'Password needs to be at least 6 characters long'
            }]
          },       
          passwordConfirm: {
            identifier: 'PasswordConfirm',
            rules: [{
              type: 'match[Password]',
              prompt: 'Password don\'t match'
            }]
          }
        }, {
          on: 'blur',
          inline: 'true'
        });
        
        $(".close.icon").click(function(){
          $(this).parent().hide();
        });
        
      }(jQuery));
    </script>